### ISSUE TITLE
Support for multiple reference containers.

### ISSUE THREAD

**Issue by jkbonfield** [enasequence/cramtools#28]
If I have a bunch of reads with 1 read per reference, htslib/scramble on the 3rd such occurance in quick succession will switch to multi-ref mode were the container reference sequence id is set to -2.  htslib/test/ce#5b.sam is an example of this.

This used to work with cramtools-2.1 but seems to fail with 3.0.

A trivial example with cram_dump output for the 3rd container:

```
Container pos 11030 size 286
    Ref id:            -2
    Ref pos:           0 + 0
    Rec counter:       2
    No. recs:          1
    No. bases          10
    No. blocks:        5
    No. landmarks:     1
    {164}
...
Rec 1/1 at 0,7
BF = 0 => SAM 0x0 (ret 0, out_sz 1)
CF = 3 (ret 0, out_sz 1)
RI = 2 (ret 0, out_sz 1)
RL = 10 (ret 0, out_sz 1)
AP = 1 (ret 0, out_sz 1)
RG = -1 (ret 0, out_sz 1)
RN = III (ret 0, out_sz 3)
Detached
MF = 0 (ret 0, out_sz 1)
NS = -1 (ret 0, out_sz 1)
NP = 0 (ret 0, out_sz 1)
TS = 0 (ret 0, out_sz 1)
TL = 0 (ret 0, out_sz 1)
FN = 0 (ret 0, out_sz 1)
MQ = 1 (ret 0, out_sz 1)
QS =            (ret 0, out_sz 10)
```

The corresponding SAM record for this looks like:

```
III     0       s3      1       1       10M     *       0       0       AAAAAAAAAA      *
```

Cramtools 3.0 extracts this as:

```
III     0       s3      1       1       10M     *       0       0       NNNNNNNNNN      ??????????
```

NB this also shows another issue.  The quality should be "*" for this case, although I am unsure if that is due to my encoding or your decoding!

Note that the CRAM specification is perhaps a bit ambiguous.  I set ref id to -2 and pos/span to 0 as they have no meaning for ref -2.  Unless that is you interpret the pos/span 0 to indicate unmapped reads.  I assume that statement in the spec is simply there to indicate with ref id -1 we'd *expect* those fields to be zero rather than those fields being zero *implies* unmapped data.  It should probably be replaced with text like "the alignment start position or 0 when reference sequence id < 0".

**Comment by vadimzalunin** [comment]
can scramble switch back to single ref later?

**Comment by jkbonfield** [comment]
On Thu, Apr 09, 2015 at 07:29:52AM -0700, Vadim Zalunin wrote:
> can scramble switch back to single ref later?

It would be justified in doing so as the specification allows it, but
in the current implementation it does not.  Once the flag for
"multi-ref" has been set, it stays set.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by vadimzalunin** [comment]
i though multi-ref flag scope is container, not file.

**Comment by jkbonfield** [comment]
On Thu, Apr 09, 2015 at 08:37:40AM -0700, Vadim Zalunin wrote:
> i though multi-ref flag scope is container, not file.

It is, but my implementation simply handles it per file as a means to
detect whether an excessive number of containers are being produced.

This is mainly because of the code flow.  I don't read 10k reads and
then try to work out how to best deal with them.  Rather I keep
pushing reads one at a time into the CRAM encoder and let it decide
when it is time to start a new container.

It'll normally do this once every so many reads (eg 10,000) or once
every reference sequence change, but if it detects changes coming
thick and fast it'll change tactics and start shoehorning multiple
references into a single container.

This is appropriate if the data is unsorted or if it has thousands of
low coverage references (eg a noisy assembly). Obviously each and
every container has the flags set appropriately, so this is purely an
implementation thing rather than a file format thing.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jkbonfield** [comment]
It looks like this problem has been fixed in one of the updates, so closing the issue.

For reference and an easy cut-n-paste contents to test with:

```
jkb@seq3a[htslib/test] cat a.sam
@SQ     SN:CHROMOSOME_I LN:1009800
@SQ     SN:CHROMOSOME_II        LN:5000
@SQ     SN:CHROMOSOME_III       LN:5000
@SQ     SN:CHROMOSOME_IV        LN:5000
@SQ     SN:CHROMOSOME_V LN:5000
I       0       CHROMOSOME_I    1       1       10M     *       0       0       AAAAAAAAAA     ##########
II      0       CHROMOSOME_II   1       1       10M     *       0       0       AAAAAAAAAA     ##########
III     0       CHROMOSOME_III  1       1       10M     *       0       0       AAAAAAAAAA     ##########
IV      0       CHROMOSOME_IV   1       1       10M     *       0       0       AAAAAAAAAA     ##########
V       0       CHROMOSOME_V    1       1       10M     *       0       0       AAAAAAAAAA     ##########
```
